### GLOBAL

compatibility_date = "2021-12-15"
name = "my-remix"
type = "javascript"
account_id = "6cb694a6c805ce2a4d49cc329f97e470"

### DEVELOPMENT

workers_dev = true
#route = "https://example.com/*"
#zone_id = ""

[vars]
NAME="workers-development"

[[kv_namespaces]]
binding = "KV"
id = "ac218cc7d8af4e6b90ea7b9fa851ed51"
preview_id = "ac218cc7d8af4e6b90ea7b9fa851ed51"

[durable_objects]
bindings = [
    { name = "EXAMPLE", class_name = "ExampleDO" },
]

[build]
command = "rm -rf build public/_worker.js public/static/build && yarn build:wrangler"

[build.upload]
format = "modules"
dir = "public"
main = "./_worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[site]
bucket = "./public"
entry-point = "."
exclude = ["/_*"]

### PRODUCTION

[env.production]
workers_dev = true
#route = "https://example.com/*"
#zone_id = ""

[env.production.vars]
NAME="workers-production"

[[env.production.kv_namespaces]]
binding = "KV"
id = "966631e52a2e40b3b03ac11f4bf9deeb"

[env.production.durable_objects]
bindings = [
    { name = "EXAMPLE", class_name = "ExampleDO" },
]

### MINIFLARE

[miniflare]
kv_persist = true
durable_objects_persist = true