### GLOBAL

compatibility_date = "2021-12-02" # https://developers.cloudflare.com/workers/platform/compatibility-dates
name = "my-remix"
type = "javascript"
account_id = "6cb694a6c805ce2a4d49cc329f97e470" # CF Dashboard
usage_model = 'bundled' #https://developers.cloudflare.com/workers/platform/pricing#workers


### DEVELOPMENT

# Domains

workers_dev = true # <name>.<your-subdomain>.workers.dev
#route = "https://example.com/*"
#zone_id = "CF Dashboard"

# Bindings. Accessible under env in worker & durable object code

[vars]
NAME="development" # env.NAME

[[kv_namespaces]]
binding = "KV" # env.KV
id = "ac218cc7d8af4e6b90ea7b9fa851ed51" # create with wrangler or CF Dashboard > Workers -> KV
preview_id = "ac218cc7d8af4e6b90ea7b9fa851ed51"

[[durable_objects.bindings]]
name = "EXAMPLE" # env.EXAMPLE
class_name = "ExampleDO"

# build everything and upload public assets

[build]
command = "rm -rf dist/* build public/static/build && yarn build && esbuild src/worker.ts --outfile=dist/worker.mjs --define:process.env.NODE_ENV=\\\"production\\\" --external:__STATIC_CONTENT_MANIFEST --bundle --format=esm --minify"
upload = { format = "modules", main="./worker.mjs" }

[site]
bucket = "./public"
entry-point = "."


### PRODUCTION

# Domains

[env.production]
workers_dev = true # use route/zone_id for production
#route = "https://example.com/*"
#zone_id = "CF Dashboard"

# Bindings. Accessible under env in worker & durable object code

[env.production.vars]
NAME="production" # env.name

[[env.production.kv_namespaces]]
binding = "KV" # env.KV
id = "966631e52a2e40b3b03ac11f4bf9deeb" # create with wrangler or CF Dashboard > Workers -> KV

[[env.production.durable_objects.bindings]]
name = "EXAMPLE" # env.EXAMPLE
class_name = "ExampleDO"


### MINIFLARE

[miniflare]
kv_persist = true
durable_objects_persist = true