### GLOBAL

compatibility_date = "2021-12-15"
name = "my-remix-dev"
type = "javascript"
account_id = "6cb694a6c805ce2a4d49cc329f97e470"


### DEVELOPMENT

# Domains

workers_dev = true
#route = "https://example.com/*"
#zone_id = ""

# Bindings.

[vars]
NAME="development"

#[[kv_namespaces]]
#binding = "KV"
#id = ""
#preview_id = ""

#[durable_objects]
#bindings = [
#    { name = "EXAMPLE", class_name = "ExampleDO" },
#]

[build]
command = "rm -rf build public/_worker.js public/static/build && yarn build"

[build.upload]
format = "modules"
dir = "public"
main = "./_worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[site]
bucket = "./public"
entry-point = "."
exclude = ["_worker.js"]

### PRODUCTION

### MINIFLARE

[miniflare]
kv_persist = true
durable_objects_persist = true