compatibility_date = "2021-11-30"
name = "my-remix"
type = "javascript"
usage_model = 'bundled'

account_id = "6cb694a6c805ce2a4d49cc329f97e470"
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "rm -rf dist/* build public/static/build && npm run build && esbuild src/worker.ts --outfile=dist/worker.mjs --define:process.env.NODE_ENV=\\\"production\\\" --external:__STATIC_CONTENT_MANIFEST --bundle --format=esm --minify"
upload = { format = "modules", main="./worker.mjs" }